//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.11 at 01:55:38 AM CEST 
//


package com.agent.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.agent.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    private final static QName _SendMessageRequest_QNAME = new QName("http://messageService.com/message", "sendMessageRequest");
    private final static QName _SendMessageResponse_QNAME = new QName("http://messageService.com/message", "sendMessageResponse");
    private final static QName _AddCommentRequest_QNAME = new QName("http://adService.com/comment", "addCommentRequest");
    private final static QName _AddCommentResponse_QNAME = new QName("http://adService.com/comment", "addCommentResponse");
    private final static QName _AddModelRequest_QNAME = new QName("http://adService.com/comment", "addModelRequest");
    private final static QName _AddModelResponse_QNAME = new QName("http://adService.com/comment", "addModelResponse");


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.agent.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ad }
     * 
     */
    public Ad createAd() {
        return new Ad();
    }

    /**
     * Create an instance of {@link Car }
     * 
     */
    public Car createCar() {
        return new Car();
    }

    /**
     * Create an instance of {@link Brand }
     * 
     */
    public Brand createBrand() {
        return new Brand();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link Fuel }
     * 
     */
    public Fuel createFuel() {
        return new Fuel();
    }

    /**
     * Create an instance of {@link GearShift }
     * 
     */
    public GearShift createGearShift() {
        return new GearShift();
    }

    /**
     * Create an instance of {@link CarClass }
     * 
     */
    public CarClass createCarClass() {
        return new CarClass();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link PriceList }
     * 
     */
    public PriceList createPriceList() {
        return new PriceList();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public com.agent.model.Message createMessage() {
        return new com.agent.model.Message();
    }
    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addModelRequest")
    public JAXBElement<com.agent.wsdl.Model> addModelRequest(com.agent.wsdl.Model addModelRequest) {
        return new JAXBElement<com.agent.wsdl.Model>(_AddModelRequest_QNAME, com.agent.wsdl.Model.class, null, addModelRequest);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addModelResponse")
    public JAXBElement<Long> addModelResponse(Long addModelResponse) {
        return new JAXBElement<>(_AddModelResponse_QNAME, Long.class, null, addModelResponse);
    }


    @XmlElementDecl(namespace = "http://messageService.com/message", name = "sendMessageRequest")
    public JAXBElement<com.agent.wsdl.Message> createSendMessageRequest(com.agent.wsdl.Message sendMessageRequest) {
        return new JAXBElement<com.agent.wsdl.Message>(_SendMessageRequest_QNAME, com.agent.wsdl.Message.class, null, sendMessageRequest);
    }

    @XmlElementDecl(namespace = "http://messageService.com/message", name = "sendMessageResponse")
    public JAXBElement<Long> createSendMessageResponse(Long sendMessageResponse) {
        return new JAXBElement<>(_SendMessageResponse_QNAME, Long.class, null, sendMessageResponse);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addCommentRequest")
    public JAXBElement<com.agent.wsdl.Comment> addCommentRequest(com.agent.wsdl.Comment addCommentRequest) {
        return new JAXBElement<com.agent.wsdl.Comment>(_AddCommentRequest_QNAME, com.agent.wsdl.Comment.class, null, addCommentRequest);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addCommentResponse")
    public JAXBElement<Long> addCommentResponse(Long addCommentResponse) {
        return new JAXBElement<>(_AddCommentResponse_QNAME, Long.class, null, addCommentResponse);
    }

}
