//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.27 at 12:21:33 AM CEST 
//


package com.adService.soap;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.agent.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AddCommentRequest_QNAME = new QName("http://adService.com/comment", "addCommentRequest");
    private final static QName _AddCommentResponse_QNAME = new QName("http://adService.com/comment", "addCommentResponse");
    private final static QName _AddModelRequest_QNAME = new QName("http://adService.com/comment", "addModelRequest");
    private final static QName _AddModelResponse_QNAME = new QName("http://adService.com/comment", "addModelResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.agent.wsdl
     * 
     */
    public ObjectFactory() {
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addCommentRequest")
    public JAXBElement<Comment> addCommentRequest(Comment addCommentRequest) {
        return new JAXBElement<Comment>(_AddCommentRequest_QNAME, Comment.class, null, addCommentRequest);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addCommentResponse")
    public JAXBElement<Long> addCommentResponse(Long addCommentResponse) {
        return new JAXBElement<>(_AddCommentResponse_QNAME, Long.class, null, addCommentResponse);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addModelRequest")
    public JAXBElement<com.adService.soap.Model> addModelRequest(com.adService.soap.Model addModelRequest) {
        return new JAXBElement<com.adService.soap.Model>(_AddModelRequest_QNAME, com.adService.soap.Model.class, null, addModelRequest);
    }

    @XmlElementDecl(namespace = "http://adService.com/comment", name = "addModelResponse")
    public JAXBElement<Long> addModelResponse(Long addModelResponse) {
        return new JAXBElement<>(_AddModelResponse_QNAME, Long.class, null, addModelResponse);
    }

}
