//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 09:43:21 PM CEST 
//


package com.messageService.soap;

import com.messageService.model.Message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the com.messageservice.message package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private interface QNames {

        QName SendMessageRequest = new QName("http://messageService.com/message", "sendMessageRequest");
        QName SendMessageResponse = new QName("http://messageService.com/message", "sendMessageResponse");
        QName commonFault = new QName("http://messageService.com/message", "commonFault");
    }
    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.messageservice.message
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Message }
     *
     */
    public Message createMessage() {
        return new Message();
    }

    @XmlElementDecl(namespace = "http://messageService.com/message", name = "sendMessageRequest")
    public JAXBElement<Message> createSendMessageRequest(Message sendMessageRequest) {
        return new JAXBElement<>(QNames.SendMessageRequest, Message.class, null, sendMessageRequest);
    }

    @XmlElementDecl(namespace = "http://messageService.com/message", name = "sendMessageResponse" )
    public JAXBElement<Long> createSendMessageResponse(Long sendMessageResponse) {
        return new JAXBElement<>(QNames.SendMessageResponse, Long.class, null, sendMessageResponse);
    }

    @XmlElementDecl(namespace = "http://messageService.com/message", name = "commonFault")
    public JAXBElement<ErrorResponse> createCommonFault(ErrorResponse value) {
        return new JAXBElement<>(QNames.commonFault, ErrorResponse.class, null, value);
    }

}